"""empty message

Revision ID: 0e8a9e949e23
Revises: 9d5a42717510
Create Date: 2023-07-25 15:25:36.185608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8a9e949e23'
down_revision = '9d5a42717510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # op.execute("UPDATE invoices SET enable_downloads = False") <----- To set all defaults to False
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
